import Link from "next/link"
import { redirect } from "next/navigation"
import { Shell } from "@/components/shell"
import { getSession } from "@/lib/session"
import { ATLAS_SPEC } from "@/lib/portfolio-spec"

export default async function GovernancePage() {
  const session = await getSession()
  if (!session) redirect("/login?portfolio=atlas-core")
  return <Shell title="Constitution" subtitle="Atlas Core v3.1 · the rules behind every recommendation" userName={session.name} isAdmin={session.role === "admin"}>
    <div className="space-y-6">
      <section className="card-lux p-6 md:p-8"><p className="ph-eyebrow">David’s Atlas Core</p><h1 className="text-3xl font-bold mt-2">Own global growth. Control overlapping risk.</h1><p className="text-muted-foreground mt-3 max-w-3xl">The portfolio seeks a 10% planning return without pretending that target is guaranteed. It stays invested through crashes, rebalances with contributions first, and judges concentration by the companies and sectors owned through every ETF—not ticker labels alone.</p><div className="mt-5 flex gap-3 flex-wrap"><Link className="button-lux" href="/atlas-core-constitution.html" target="_blank">Read or download the full constitution</Link><Link className="button-lux button-lux-secondary" href="/mission-control">Open Mission Control</Link></div></section>
      <section className="grid md:grid-cols-5 gap-3">{ATLAS_SPEC.funds.map(f => <article key={f.ticker} className="card-lux p-5"><p className="font-data text-xs text-primary font-bold">{f.ticker}</p><p className="text-3xl font-bold mt-2">{f.target}%</p><p className="text-sm font-semibold mt-2">Constitutional holding</p><p className="text-xs text-muted-foreground mt-2">Soft {Math.max(0, f.target-f.band)}–{f.target+f.band}% · hard {f.hardFloor ?? 0}–{f.hardCap}%</p></article>)}</section>
      <section className="grid lg:grid-cols-2 gap-5"><article className="card-lux p-6"><h2 className="text-xl font-bold">What to do</h2><ol className="mt-4 space-y-3 text-sm"><li>1. Refresh IBKR holdings, prices, transactions, dividends, contributions and cost basis.</li><li>2. Refresh look-through sources before acting on concentration warnings.</li><li>3. Correct hard breaches before making discretionary additions.</li><li>4. Route new cash to the furthest-underweight eligible holding.</li><li>5. Buy whole shares only; keep unused money in the DCA cash bank for the next month.</li><li>6. Sell only for a constitutional breach, a documented thesis failure, or the approved legacy migration.</li></ol></article><article className="card-lux p-6"><h2 className="text-xl font-bold">What not to do</h2><ul className="mt-4 space-y-3 text-sm"><li>• Do not sell because markets fell or headlines are frightening.</li><li>• Do not add EQAC or SMH when their combined or look-through limits are paused.</li><li>• Do not treat USD Treasury bills as an SGD liability hedge.</li><li>• Do not erase legacy holdings before their sales settle and cost-basis history is preserved.</li><li>• Do not change targets from the app; amend the constitution and record the reason.</li></ul></article></section>
      <section className="card-lux p-6"><h2 className="text-xl font-bold">Governance cadence</h2><div className="grid md:grid-cols-3 gap-4 mt-4 text-sm"><div><b>Monthly</b><p className="text-muted-foreground">Reconcile data, route the contribution, preserve the residual bank.</p></div><div><b>Quarterly</b><p className="text-muted-foreground">Refresh fund factsheets and look-through weights; review soft warnings.</p></div><div><b>Annually</b><p className="text-muted-foreground">Review objectives, tax domicile, instruments and constitution. No automatic target changes.</p></div></div></section>
    </div>
  </Shell>
}
