import {Shell} from "@/components/shell"
import {AllocationDonut} from "@/components/charts/allocation-donut"
import {DownloadReportCard} from "@/components/reports/download-report-card"
import {RefreshLookThroughButton} from "@/components/reports/refresh-look-through-button"
import {LookThroughReconciliation} from "@/components/reports/look-through-reconciliation"
import {getSbrReportData} from "@/lib/reports/sbr-report-data"
import {formatCurrency} from "@/lib/utils"

export async function SbrReportPage({userId,userName,isAdmin}:{userId:string;userName:string;isAdmin:boolean}){
 const d=await getSbrReportData(userId,"monthly")
 return <Shell title="Look-through" subtitle="Silicon Brick Road · what every fund owns underneath" userName={userName} isAdmin={isAdmin} constitutionId="silicon-brick-road"><div className="report-deck">
  <section className="report-hero"><div><p>PORTFOLIO X-RAY</p><h1>What Dami owns underneath.</h1><span>An ETF is a box containing many investments. This page opens every box, combines repeated exposures and shows the arithmetic behind each total.</span><RefreshLookThroughButton compact lastUpdated={null}/></div><AllocationDonut data={d.positions.map(p=>({ticker:p.ticker,name:p.name,color:p.color,value:p.value,actualPct:p.actualPct,targetPct:p.targetPct}))} totalValue={d.totalValue} currency="SGD"/><dl><div><dt>Portfolio value</dt><dd>{formatCurrency(d.totalValue,"SGD")}</dd></div><div><dt>Health</dt><dd>{d.health.overall}/100</dd></div><div><dt>Source status</dt><dd className={d.lookThrough.stale?"down":"up"}>{d.lookThrough.freshness}</dd></div></dl></section>
  <section className="report-decision"><article><span>WHAT TO DO</span><h2>{d.nextMove.action}</h2><p>{d.nextMove.what}</p><small>{d.nextMove.why}</small></article><article><span>HOW COMPLETE IS THE VIEW?</span><h2>{d.lookThrough.unclassifiedPct.toFixed(2)}% unclassified</h2><p>Managed futures {d.lookThrough.managedFuturesPct.toFixed(2)}% · Bitcoin {d.lookThrough.cryptoPct.toFixed(2)}%</p><small>If a holding is unclassified, the app says so instead of pretending the picture is complete.</small></article></section>
  <section className="allocation-ledger"><header><p>POSITION CONTROL</p><h2>What is held versus the plan</h2></header><table><thead><tr><th>Fund</th><th>Value</th><th>Actual</th><th>Target</th><th>Drift</th><th>Status</th></tr></thead><tbody>{d.positions.map(p=><tr key={p.ticker}><td>{p.ticker}</td><td>{formatCurrency(p.value,"SGD")}</td><td>{p.actualPct.toFixed(2)}%</td><td>{p.targetPct}%</td><td>{p.drift>=0?"+":""}{p.drift.toFixed(2)}%</td><td className={p.status==="hard"?"down":p.status==="soft"?"warn":"up"}>{p.status}</td></tr>)}</tbody><tfoot><tr><td>Total</td><td>{formatCurrency(d.positions.reduce((s,p)=>s+p.value,0),"SGD")}</td><td>{d.positions.reduce((s,p)=>s+p.actualPct,0).toFixed(2)}%</td><td colSpan={3}>Reconciled to portfolio value</td></tr></tfoot></table></section>
  <div className="report-matrices"><LookThroughReconciliation title="Companies" description="Repeated companies are combined across all funds." lines={d.lookThrough.companies}/><LookThroughReconciliation title="Countries" description="Every country headline expands to the fund contributions that create it." lines={d.lookThrough.countries}/><LookThroughReconciliation title="Industries and themes" description="Technology and semiconductor lenses may overlap; each reconciles independently." lines={d.lookThrough.industries}/><LookThroughReconciliation title="Asset classes" description="Equity, Bitcoin and managed futures are shown separately." lines={d.lookThrough.assets}/></div>
  {d.lookThrough.warnings.length>0&&<section className="report-warnings"><p>REVIEW NOTES</p>{d.lookThrough.warnings.map(w=><span key={w}>{w}</span>)}</section>}
  {d.totalValue>0&&<DownloadReportCard endpoint="/api/reports/sbr" accent="sky" title="Download SBR report" subtitle="Current holdings, mandate status and reconciled look-through summary."/>}
 </div></Shell>
}
