/* eslint-disable @typescript-eslint/no-explicit-any */
import { Shell } from "@/components/shell"
import { AllocationDonut } from "@/components/charts/allocation-donut"
import { DownloadReportCard } from "@/components/reports/download-report-card"
import { getSbrReportData } from "@/lib/reports/sbr-report-data"
import { formatCurrency } from "@/lib/utils"

export async function SbrReportPage({userId,userName,isAdmin}:{userId:string;userName:string;isAdmin:boolean}) {
  const d=await getSbrReportData(userId,"monthly")
  const exposures=[d.lookThrough.topCompany,d.lookThrough.topCountry,d.lookThrough.topIndustry].filter(Boolean)
  return <Shell title="SBR Look-through Report" subtitle="Actual holdings · concentration · mandate status" userName={userName} isAdmin={isAdmin}>
    <div className="space-y-5">
      <section className="card-lux p-6"><p className="ph-eyebrow">Silicon Brick Road · flexible medium-term growth</p><div className="grid gap-5 lg:grid-cols-[1.4fr_.6fr] mt-3"><div><h1 className="text-3xl font-bold">What Dami owns underneath</h1><p className="text-muted-foreground mt-2 max-w-2xl">This report uses actual settled holdings. It does not substitute target weights when the account is empty and it does not assume a spending date.</p><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-5"><Metric label="Portfolio value" value={formatCurrency(d.totalValue,"SGD")}/><Metric label="Health" value={`${d.health.overall}/100`}/><Metric label="Hard breaches" value={String(d.hardBreaches)}/><Metric label="Soft warnings" value={String(d.softBreaches)}/></div></div><AllocationDonut data={d.positions.map(p=>({ticker:p.ticker,name:p.name,color:p.color,value:p.value,actualPct:p.actualPct,targetPct:p.targetPct}))} totalValue={d.totalValue} currency="SGD"/></div></section>
      <section className="grid lg:grid-cols-2 gap-5"><article className="card-lux p-5"><p className="ph-eyebrow">Next action</p><h2 className="text-xl font-bold mt-2">{d.nextMove.action}</h2><p className="text-sm mt-3">{d.nextMove.what}</p><p className="text-sm text-muted-foreground mt-2">{d.nextMove.why}</p></article><article className="card-lux p-5"><p className="ph-eyebrow">Mandate status</p><h2 className="text-xl font-bold mt-2">{d.governance.overall === "ok" ? "On mandate" : d.governance.overall === "watch" ? "Review required" : "Correction required"}</h2><p className="text-sm text-muted-foreground mt-3">VWRA 65% · EQAC 15% · SMH 5% · Bitcoin 5% · DBMFE 10%. No fixed end date; a genuine SGD use must be documented before de-risking.</p></article></section>
      <section className="card-lux p-5"><h2 className="text-lg font-bold">Current allocation</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-muted-foreground"><th className="py-2">Fund</th><th>Actual</th><th>Target</th><th>Drift</th><th>Status</th></tr></thead><tbody>{d.positions.map(p=><tr key={p.ticker} className="border-t border-border"><td className="py-3 font-bold">{p.ticker}</td><td>{p.actualPct.toFixed(1)}%</td><td>{p.targetPct}%</td><td>{p.drift>=0?"+":""}{p.drift.toFixed(1)}%</td><td className={p.status==="hard"?"text-red-500":p.status==="soft"?"text-amber-500":"text-green-500"}>{p.status}</td></tr>)}</tbody></table></div></section>
      <section className="card-lux p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Look-through concentration</h2><p className="text-xs text-muted-foreground mt-1">Source age and estimated values must be reviewed before a concentration-led trade.</p></div><span className={`text-xs ${d.lookThrough.stale?"text-red-500":"text-green-500"}`}>{d.lookThrough.stale?"Stale":"Current"}</span></div><div className="grid md:grid-cols-3 gap-3 mt-4">{exposures.map((x:any)=><Metric key={x.name} label={x.name} value={`${x.pct.toFixed(1)}%`}/>)}</div>{d.lookThrough.warnings.length>0&&<ul className="mt-4 space-y-2 text-sm text-amber-500">{d.lookThrough.warnings.map(w=><li key={w}>{w}</li>)}</ul>}</section>
      {d.totalValue>0&&<DownloadReportCard endpoint="/api/reports/sbr" accent="sky" title="Download SBR report" subtitle="Current holdings, mandate status and look-through summary."/>}
    </div>
  </Shell>
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-border bg-muted/20 p-3"><p className="text-[11px] text-muted-foreground">{label}</p><p className="text-lg font-bold mt-1 tabular-nums">{value}</p></div>}
