import{redirect}from"next/navigation";import{Shell}from"@/components/shell";import{getSession}from"@/lib/session";import{activePortfolioContext}from"@/lib/active-portfolio";import{getAtlasReportData}from"@/lib/reports/atlas-report-data";import{SbrReportPage}from"@/components/reports/sbr-report-page";import{AllocationDonut}from"@/components/charts/allocation-donut";import{DownloadReportCard}from"@/components/reports/download-report-card";import{RefreshLookThroughButton}from"@/components/reports/refresh-look-through-button";import{formatCurrency}from"@/lib/utils"
export default async function Reports(){const session=await getSession();if(!session)redirect("/login");const active=await activePortfolioContext(session);if(active.constitutionId==="silicon-brick-road")return <SbrReportPage userId={active.owner.id} userName={session.name} isAdmin={session.role==="admin"}/>;const d=await getAtlasReportData(active.owner.id,"monthly");return <Shell title="Atlas Look-through Report" subtitle="Actual holdings · overlap · concentration · mandate status" userName={session.name} isAdmin={session.role==="admin"}><div className="space-y-5">
 <section className="card-lux p-6"><div className="flex items-start justify-between gap-4"><div><p className="ph-eyebrow">Atlas Core · Constitution v10.4</p><h1 className="text-3xl font-bold mt-2">What David owns underneath</h1><p className="text-muted-foreground mt-2 max-w-2xl">Actual settled holdings, including transition positions. Look-through exposure is governed across ETF labels and stale sources cannot create an automatic sell instruction.</p></div><RefreshLookThroughButton compact lastUpdated={null}/></div><div className="grid gap-5 lg:grid-cols-[1.4fr_.6fr] mt-5"><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Metric label="Portfolio value" value={formatCurrency(d.totalValue,"SGD")}/><Metric label="Health" value={`${d.health.overall}/100`}/><Metric label="Hard breaches" value={String(d.hardBreaches)}/><Metric label="Soft warnings" value={String(d.softBreaches)}/></div><AllocationDonut data={d.positions.map(p=>({ticker:p.ticker,name:p.name,color:p.color,value:p.value,actualPct:p.actualPct,targetPct:p.targetPct}))} totalValue={d.totalValue}/></div></section>
 <section className="grid lg:grid-cols-2 gap-5"><article className="card-lux p-5"><p className="ph-eyebrow">Next permitted action</p><h2 className="text-xl font-bold mt-2">{d.nextMove.headline}</h2><p className="text-sm mt-3">{d.nextMove.instruction}</p><p className="text-sm text-muted-foreground mt-2">{d.nextMove.rationale}</p></article><article className="card-lux p-5"><p className="ph-eyebrow">Mandate status</p><h2 className="text-xl font-bold mt-2">{d.governance.overall==="ok"?"On mandate":d.governance.overall==="watch"?"Review required":"Correction required"}</h2><div className="mt-3 space-y-2">{d.governance.checks.filter(x=>x.status!=="ok").map(x=><p key={x.id} className={`text-sm ${x.status==="breach"?"text-red-500":"text-amber-500"}`}>{x.label}: {x.detail}</p>)}{d.governance.checks.every(x=>x.status==="ok")&&<p className="text-sm text-muted-foreground">All current allocation and look-through checks are clear.</p>}</div></article></section>
 <section className="card-lux p-5"><h2 className="text-lg font-bold">Current allocation</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-muted-foreground"><th className="py-2">Holding</th><th>Actual</th><th>Target</th><th>Drift</th><th>Status</th></tr></thead><tbody>{d.positions.map(p=><tr key={p.ticker} className="border-t border-border"><td className="py-3 font-bold">{p.ticker}</td><td>{p.actualPct.toFixed(1)}%</td><td>{p.targetPct}%</td><td>{p.drift>=0?"+":""}{p.drift.toFixed(1)}%</td><td className={p.status==="hard"?"text-red-500":p.status==="soft"?"text-amber-500":"text-green-500"}>{p.status}</td></tr>)}</tbody></table></div></section>
 <section className="grid lg:grid-cols-2 gap-5"><Exposure title="Companies" rows={d.lookThrough.companies}/><Exposure title="Sectors, themes and country" rows={d.lookThrough.sectors}/></section>
 {d.totalValue>0&&<DownloadReportCard endpoint="/api/reports/atlas" accent="violet" title="Download Atlas report" subtitle="Current holdings, mandate status and look-through summary."/>}
 </div></Shell>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-border bg-muted/20 p-3"><p className="text-[11px] text-muted-foreground">{label}</p><p className="text-lg font-bold mt-1 tabular-nums">{value}</p></div>}
function Exposure({title,rows}:{title:string;rows:Array<{key:string;label:string;pct:number;soft:number;hard:number;status:string}>}){return <article className="card-lux p-5"><h2 className="text-lg font-bold">{title}</h2><div className="mt-4 space-y-3">{rows.slice(0,8).map(x=><div key={x.key}><div className="flex justify-between gap-3 text-sm"><span>{x.label}</span><span className={x.status==="breach"?"text-red-500":x.status==="watch"?"text-amber-500":"text-muted-foreground"}>{x.pct.toFixed(1)}%</span></div><div className="mt-1 h-1.5 rounded bg-muted overflow-hidden"><div className="h-full rounded bg-primary" style={{width:`${Math.min(100,x.pct/x.hard*100)}%`}}/></div><p className="text-[10px] text-muted-foreground mt-1">watch {x.soft}% · hard {x.hard}%</p></div>)}</div></article>}
