import type { ConstitutionId } from "@/lib/constitutions"
import { ATLAS_SPEC, SBR_SPEC } from "@/lib/portfolio-spec"

export interface AppGovernanceRule {
  id:string; category:string; title:string; rule:string; why:string; appAction:string
}

export function governanceRules(id:ConstitutionId):AppGovernanceRule[]{
  const atlas=id==="atlas-core", spec=atlas?ATLAS_SPEC:SBR_SPEC
  const targets=spec.funds.map(f=>`${f.ticker} ${f.target}%`).join(", ")
  const bands=spec.funds.map(f=>`${f.ticker} ${"band" in f?`${f.target-f.band}–${f.target+f.band}`:`${f.rangeLow}–${f.rangeHigh}`}%`).join("; ")
  return [
    {id:"authority",category:"Authority",title:"The constitution wins",rule:`Use ${atlas?"Atlas v10.6":"SBR v10.5"}. If the app and constitution disagree, stop the affected instruction.`,why:"Software can contain mistakes; a versioned written mandate provides the controlling record.",appAction:"Show a blocking discrepancy and create no trade instruction."},
    {id:"universe",category:"Construction",title:"Only the approved target sleeves receive new money",rule:`Target ${targets}. Match legal name and ISIN/CUSIP, not ticker alone.`,why:"Extra tickers often duplicate existing risks and make the plan harder to control.",appAction:"Show target sleeves on the dashboard; keep legacy instruments in activity/history only."},
    {id:"bands",category:"Construction",title:"Soft bands guide contributions",rule:`Working bands: ${bands}.`,why:"Normal market movement should direct new cash rather than cause unnecessary sales.",appAction:"Route the next contribution to the furthest-underweight eligible sleeve."},
    {id:"hard",category:"Construction",title:"Hard limits require review",rule:"A hard floor or cap pauses additions and requires a written correction. It does not automatically sell.",why:"Outer limits stop a small idea from taking control while avoiding mechanical panic trades.",appAction:"Mark the breach, pause the affected purchase and explain the next permitted step."},
    {id:"lookthrough",category:"Concentration",title:"Measure what the funds own underneath",rule:"Watch/hard: company 7/9%, technology 45/50%, semiconductors 25/30%, United States 70/75%, unclassified 1/3%.",why:"Different ETFs can own the same companies, so ticker weights alone understate concentration.",appAction:"Aggregate refreshed underlying holdings and redirect new cash before considering sales."},
    {id:"freshness",category:"Data quality",title:"Stale data cannot create a sale",rule:"Warn when the oldest required source is over 35 days old; block concentration-led instructions after 75 days.",why:"An old estimate can be useful as a warning but is too weak to compel a disposal.",appAction:"Display source and as-of date; refresh before concentration-led action."},
    {id:"dca",category:"Contributions",title:"Use confirmed cash and whole shares",rule:"Add the contribution and carried cash, reserve FX and commission, buy whole units, then carry the exact residual.",why:"The app must never spend expected proceeds or pretend residual cash was invested.",appAction:"Reconcile each instruction to a unique confirmed IBKR execution."},
    {id:"settlement",category:"Contributions",title:"Sale proceeds must settle first",rule:"Lifecycle: pending sale → sold/unsettled → confirmed settled cash → reinvested.",why:"Expected proceeds can change through price, commission, tax, FX or settlement adjustments.",appAction:"Credit migration cash only from authoritative broker cash data."},
    {id:"liquidity",category:"Behaviour",title:"Personal safety comes before contributions",rule:"Green: continue. Amber: pause optional increases. Red: suspend contributions and protect essential spending.",why:"A growth portfolio cannot substitute for external emergency cash.",appAction:"Never score DBMFE, Bitcoin or an equity ETF as emergency liquidity."},
    {id:"crash",category:"Behaviour",title:"A falling price is not a sell rule",rule:"No leverage, margin or panic selling. Wait 72 hours before an unscheduled discretionary sale unless delay is unsafe.",why:"Fear makes permanent decisions feel urgent during temporary market stress.",appAction:"Show the constitutional questions and cooling-off time instead of a sell button."},
    {id:"forecast",category:"Forecasts",title:"Forecasts describe ranges, not promises",rule:"Use contribution-aware scenarios and Monte Carlo assumptions; never treat a percentile or base case as guaranteed.",why:"The model cannot know future returns, volatility, correlations, inflation or sequence.",appAction:"Show assumptions, as-of date, difficult/base/strong paths and model limitations."},
    {id:"returns",category:"Performance",title:"Separate cash flows from investment return",rule:"Contributions, withdrawals and migration trades are not gains or losses.",why:"Raw value changes can make a deposit look like performance.",appAction:"Use cash-flow-adjusted return where available and label raw value movement honestly."},
    {id:"history",category:"Records",title:"Never rewrite instrument history",rule:atlas?"Keep VT, VWO, QQQM, US SMH and GBTC with their original basis and flows; retain IBIT as the target Bitcoin vehicle.":"Keep any closed or out-of-plan instrument with its original basis and flows.",why:"A replacement is a new purchase, not a renamed old security.",appAction:"Close absent positions only from an authoritative complete IBKR report; never delete their ledger."},
    {id:"review",category:"Reviews",title:"Review at the right rhythm",rule:"Monthly reconciliation; quarterly bands and sources; annual purpose, instruments, beneficiaries and legal/tax review.",why:"A fixed rhythm reduces both neglect and compulsive tinkering.",appAction:"Surface due items and archive completed evidence."},
    {id:"amend",category:"Amendments",title:"Change rules slowly",rule:"A material change needs written evidence, a version increment and a 30-day cooling-off period except genuine emergencies.",why:"Excitement, fear and recent performance are poor constitution writers.",appAction:"Record owner, reason, authority, start date, expiry and remediation."},
  ]
}
